More cost estimation
smartcontractkit/functions-hardhat-starter-kit pull request #94
Opened 2023-02-18 02:02 UTC by justinkaseman

2023-02-24 12:40 UTC, Coollaitar commented
Can anybody explain to me what basically we have to do in this issue ` Cost prompt util for all write commands`?

2023-02-24 12:41 UTC, Coollaitar commented
> Can anybody explain to me what basically we have to do in this issue ` Cost prompt util for all write commands`?

I will try my best to help you with this issue

2023-02-26 20:37 UTC, bolekk requested changes
The utils are great!

2023-02-26 20:37 UTC, bolekk commented on tasks/Functions-client/request.js
> +        `Subscription ${subscriptionId} does not have sufficient funds. The estimated cost is ${estimatedCostJuels} Juels LINK, but the subscription only has a balance of ${linkBalance} Juels LINK`
We need to divide it by 10^18 and show a decimal LINK, otherwise the numbers are too big to eyeball

2023-03-15 18:41 UTC, KuphJr commented on tasks/Functions-client/request.js
> +    await utils.prompt(
Users will receive 2 prompts in order to initiate a request.  Can we combine these so they only have to confirm once?

2023-03-15 19:02 UTC, merged